name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install intakebuilder 
      run: |
        conda config --add channels noaa-gfdl
        conda config --append channels conda-forge
        conda install intakebuilder -c noaa-gfdl

    - name: Download sample cloud fields mid_cld_amt, low_cld_amt, high_cld_amt
      run: curl -O --verbose --ipv4 --connect-timeout 8 --max-time 1200 --retry 128 ftp://nomads.gfdl.noaa.gov/1/oar.gfdl.mdtf/MDTF-examples/GFDL-CM4/data/atmos/ts/monthly/1yr/atmos.198001-198012.high_cld_amt.nc

    

