# Installs the Python dependencies and runs the freanalysis_clouds plugin.
name: Test freanalysis_clouds plugin

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        conda config --add channels noaa-gfdl
        conda config --append channels conda-forge
        conda install noaa-gfdl::catalogbuilder -n analysis-scripts
        conda activate analysis-scripts
        pip install --upgrade pip
        cd analysis-scripts; pip install .; cd ..
        cd figure_tools; pip install .; cd ..
        cd freanalysis; pip install .; cd ..
        cd freanalysis_clouds; pip install .; cd ..
        
    - name: Test freanalysis_clouds
      run: |
        $CONDA/bin/python -m pytest tests
