name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install intakebuilder 
      run: |
        conda config --add channels noaa-gfdl
        conda config --append channels conda-forge
        conda install intakebuilder -c noaa-gfdl
    - name: Download sample cloud fields mid_cld_amt, low_cld_amt, high_cld_amt
      run: |
           mkdir -p archive/oar.gfdl.mdtf/MDTF-examples/mdtf-time-slice-example/gfdl.ncrc5-deploy-prod-openmp/pp/atmos/ts/monthly/1yr/ && curl -O ftp://nomads.gfdl.noaa.gov/1/oar.gfdl.mdtf/MDTF-examples/GFDL-CM4/data/atmos/ts/monthly/1yr/atmos.198001-198012.high_cld_amt.nc
           ls archive/oar.gfdl.mdtf/MDTF-examples/mdtf-time-slice-example/gfdl.ncrc5-deploy-prod-openmp/pp/atmos/ts/monthly/1yr/
    - name: 'Generate catalog'
      run: |
        $CONDA/envs/catalogbuilder/bin/python ray_cloud.py 
    - name: upload-artifacts1
      uses: actions/upload-artifact@v4
      with:
          name: workflow-artifacts1 
          path: |
            cats/gfdl_analysis_citest.csv
            cats/gfdl_analysis_citest.json
            cats/gfdl_analysis_citest.csv
            cats/gfdl_analysis_citest.json
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4
    

